[cf]
api_base_url = "https://api.cloudflare.com/client/v4"
api_token = ""

[[cf.records]]
record_name = "git.distempr.name"
zone_id = ""
record_id = ""

[[cf.records]]
record_name = "git.durl.name"
zone_id = ""
record_id = ""
