#!/usr/bin/env python3

import tomllib

import requests


with open("/etc/updatedns.toml", "rb") as f:
    config = tomllib.load(f)

ip = requests.get(
    config["aws"]["metadata_url"] + "public-ipv4"
).text

for record in config["cf"]["records"]:
    requests.patch(
        f'{config["cf"]["api_base_url"]}/zones/{record["zone_id"]}/dns_records/{record["record_id"]}',
        json={
            "name": record["record_name"],
            "type": "A",
            "content": ip
        },
        headers={
            "Authorization": "Bearer " + config["cf"]["api_token"]
        }
    )
